version: "3.8"

services:
  ssh-honeypot:
    build:
      context: .
      dockerfile: containers/Dockerfile.ssh
    container_name: real-ssh-honeypot
    ports:
      - "2222:22"
    volumes:
      - ./bait_files:/home/admin/bait:ro
    restart: unless-stopped
